### ISSUE TITLE
conbee ii firmware seems out of date

### ISSUE THREAD

**Issue by alinelena** [marthoc/docker-deconz#180] opened 2019-11-23 17:04 UTC
with the latest docker imaged pulled I get when i check the firmware

```
16:48:27:689 GW update firmware found: /usr/share/deCONZ/firmware/deCONZ_ConBeeII_0x26490700.bin.GCF
16:48:27:689 GW firmware version: 0x26490700
16:48:27:689 GW firmware version is up to date: 0x26490700
16:52:27:504 GW firmware version: 0x26490700
16:52:27:504 GW firmware version is up to date: 0x26490700
16:56:27:497 GW firmware version: 0x26490700
16:56:27:497 GW firmware version is up to date: 0x26490700
17:00:27:495 GW firmware version: 0x26490700
17:00:27:495 GW firmware version is up to date: 0x26490700
```

however if I check here http://deconz.dresden-elektronik.de/deconz-firmware/
more recent firmware seems to be available

**Comment by DAD405** [comment] 2019-12-08 20:54
I Cam confirm.
Just bought a Conbee2 Stick what had newer Firmware already flashed by Vendor.

19:21:40:969 unlocked max nodes: 200
19:21:41:394 GW update firmware found: /usr/share/deCONZ/firmware/deCONZ_ConBeeII_0x26490700.bin.GCF
19:21:41:394 GW firmware version: 0x264a0700
19:21:41:394 GW firmware version is up to date: 0x264a0700
19:21:41:477 Device protocol version: 0x010B

**Comment by pmoerz** [comment] 2020-03-06 07:37
i have the same problem like alinelena. cant update and the logs dont show that theres a new version available.

**Comment by volschin** [comment] 2020-03-06 07:57
Iirc this always worked in this way, as the new firmwares are beta and only stable updates are suggested. But it would be nice to have the ability to switch between a stable/beta Channel.

**Comment by manup** [comment] 2020-03-06 08:06
Hi, small note: 0x26490700 and 0x264a0700 and are both recommended for know.

The newer versions are part of an investigation in routing issues and don't work on all setups.
I would highly recommend to wait for update until the issue is resolved and the new stable firmware is released officially. 

https://github.com/dresden-elektronik/deconz-rest-plugin/issues/1261

**Comment by alinelena** [comment] 2020-03-06 08:22
@manup the question is not about using beta firmware, is simply about updating to 0x264a0700 which somehow seems not to be possible. I had no issues updating firmware on conbee I.

**Comment by manup** [comment] 2020-03-06 08:30
Did you try the manual approach?

https://github.com/marthoc/docker-deconz#updating-conbeeraspbee-firmware

deCONZ does report that 0x26490700 is up to date, since the 0x264a0700 version isn't needed for deCONZ (it has only a fix used by the Mozilla IoT gateway).

**Comment by alinelena** [comment] 2020-03-06 08:34
@manup yes tried the manual and failed. I may try again over the weekend.

**Comment by SAOPP** [comment] 2020-03-27 16:37
Hi guys! Yes, any of my devices are not show any updatesm raspbee and conbee2.

**Comment by marthoc** [comment] 2020-05-27 21:23
Closing this issue as likely related to #228 - follow that thread for updates.

**Closed** 2020-05-27 21:23 UTC
