### ISSUE TITLE
Docker search on false ttyACM

### ISSUE THREAD

**Issue by Thomasdmm** [marthoc/docker-deconz#325] opened 2020-12-03 11:31 UTC
Hello I have this configuration 
![image](https://user-images.githubusercontent.com/53251953/101012534-445e5780-3563-11eb-8484-0a301105da8c.png)
But In Diary i have this message
![image](https://user-images.githubusercontent.com/53251953/101012630-66f07080-3563-11eb-890b-3a3591cd72f3.png)

I check the conbee stick i in ttyACM2 
I change chmod in 777 for this tty
What is the problem ?

**Comment by Jo-Be-Co** [comment] 2020-12-03 12:02
Seem like you were adding an environment variable called `-e DECONZ_DEVICE`. You should check if you used to many quotes or have an addidional `-e` in your config-files ...

**Comment by Thomasdmm** [comment] 2020-12-03 12:17
I added this line following the problem encountered to see if it could not improve the configuration. But the result does not change with or without this variable which is the only one with an -e

**Comment by Jo-Be-Co** [comment] 2020-12-03 13:22
@Thomasdmm you missed the line.

**Comment by Thomasdmm** [comment] 2020-12-03 13:47
the line with : -`e DECONZ_DEVICE /dev/ttyACM2`

**Comment by Jo-Be-Co** [comment] 2020-12-03 13:53
Is this part of your command-line or a config-file?

**Comment by Thomasdmm** [comment] 2020-12-03 14:00
I add this command in this windows. I don't have create the docker with a command but with the docker application in my synology nas
![image](https://user-images.githubusercontent.com/53251953/101027434-4bdc2b80-3578-11eb-9ce2-824448c57eb8.png)

**Comment by Jo-Be-Co** [comment] 2020-12-04 09:44
In the container config on your NAS you need to specify the name of variable without an `-e`.

So you have to stop the container and enter the edit-mode. There you have to delete the `-e` ... and also the space:
![image](https://user-images.githubusercontent.com/22118442/101148133-919eff80-361d-11eb-9662-867412632d81.png)

**Comment by Jo-Be-Co** [comment] 2020-12-10 16:08
@Thomasdmm if your problem is solved you may leave a note and close this issue.

**Comment by Thomasdmm** [comment] 2020-12-10 16:26
Hello I remove the command with -e and keep only the command for DECONZ_DEVICE /dev/ttyACM2 
I restart the container but nothing change :(

**Comment by RikP** [comment] 2020-12-15 11:34
i am experiencing the exact same problem. I run the container with:
```
/docker run -d --name='deconz' --net='host' -e TZ="Europe/Berlin" -e 'DECONZ_WEB_PORT'='9080' -e 'DECONZ_WS_PORT'='9443' -e 'DEBUG_INFO'='1' -e 'DEBUG_APS'='0' -e 'DEBUG_ZCL'='0' -e 'DEBUG_ZDP'='0' -e 'DEBUG_OTAU'='0' -e 'DECONZ_DEVICE'='/dev/serial/by-id/usb-dresden_elektronik_ingenieurtechnik_GmbH_ConBee_II_DE2193941-if00' -e 'DECONZ_VNC_MODE'='1' -e 'DECONZ_VNC_PORT'='9900' -e 'DECONZ_VNC_PASSWORD'='' -e 'DECONZ_UPNP'='0' -v '/mnt/user/appdata/deCONZ/':'/opt/deconz':'rw' --device='/dev/serial/by-id/usb-dresden_elektronik_ingenieurtechnik_GmbH_ConBee_II_DE2193941-if00' 'marthoc/deconz:latest'
```

In my log i see it also trying to connect to /dev/ttyACM0 still:
```
12:32:27:792 HTTP Server listen on address 0.0.0.0, port: 9080, root: /usr/share/deCONZ/webapp/
12:32:27:799 CTRL. 3.27.212:32:27:821 COM: use stable device path /dev/serial/by-id/usb-dresden_elektronik_ingenieurtechnik_GmbH_ConBee_II_DE2193941-if00
12:32:27:835 dev can't create file: /dev/ttyACM0 via mknod (missing permissions)
12:32:27:849 dev can't create file: /dev/ttyACM0 via mknod (missing permissions)
12:32:27:849 ZCLDB init file /root/.local/share/dresden-elektronik/deCONZ/zcldb.txt
12:32:27:894 parent process /bin/sh
12:32:27:894 gw run mode: docker
12:32:27:894 GW sd-card image version file does not exist: /root/.local/share/dresden-elektronik/deCONZ/gw-version

12:32:27:894 DB sqlite version 3.27.2

12:32:27:895 DB PRAGMA page_count: 0
12:32:27:895 DB PRAGMA page_size: 4096
12:32:27:895 DB PRAGMA freelist_count: 0
12:32:27:895 DB file size 0 bytes, free pages 0
12:32:27:895 DB PRAGMA user_version: 0
12:32:27:895 DB upgrade to user_version 1
12:32:28:392 DB write sqlite user_version 1
12:32:28:422 DB PRAGMA user_version: 1
12:32:28:423 DB upgrade to user_version 2
12:32:28:470 DB write sqlite user_version 2
12:32:28:493 DB PRAGMA user_version: 2
12:32:28:493 DB upgrade to user_version 6
12:32:28:563 DB write sqlite user_version 6
12:32:28:587 DB PRAGMA user_version: 6
12:32:28:587 DB upgrade to user_version 7
12:32:28:637 DB write sqlite user_version 7
12:32:28:665 DB PRAGMA user_version: 7
12:32:28:665 DB cleanup
12:32:28:665 DB create temporary views
12:32:28:666 started websocket server at port 9443
12:32:28:667 create default username and password
12:32:28:667 [INFO] - Found file containing button maps. Parsing data...
12:32:28:668 [WARNING] - Button map 'sunricherCCTMap' in JSON file has no assigned ModelIDs. Skip loading button map...

12:32:28:670 [INFO] - Button maps loaded.
12:32:28:671 dlg action: Read binding table
12:32:28:671 found node plugin: libde_rest_plugin.so - REST API Plugin
12:32:28:672 found node plugin: libde_signal_plugin.so - Signal Monitor Plugin
12:32:28:694 found node plugin: libstd_otau_plugin.so - STD OTAU Plugin
12:32:28:711 dev can't create file: /dev/ttyACM0 via mknod (missing permissions)
12:32:28:727 dev can't create file: /dev/ttyACM0 via mknod (missing permissions)
12:32:29:746 dev can't create file: /dev/ttyACM0 via mknod (missing permissions)
12:32:29:760 dev can't create file: /dev/ttyACM0 via mknod (missing permissions)
12:32:29:776 device disconnected reason: 4, index: 0
12:32:30:683 wait reconnect 15 seconds
```

**Comment by Thomasdmm** [comment] 2020-12-15 11:41
Helle When in ssh command you go to the dev repertories did you found the /dev/serial/by-id/usb-dresden_elektronik_ingenieurtechnik_GmbH_ConBee_II_DE2193941-if00 ???

I found only ttyACM0 ttyACM1 and ttyACM2 for the USB component

**Comment by RikP** [comment] 2020-12-15 11:49
yes it is there:
![image](https://user-images.githubusercontent.com/941405/102211509-fe46b380-3ed3-11eb-9ead-ebf51c3645f9.png)

**Comment by RikP** [comment] 2020-12-15 13:37
Seems this is the same issue: https://github.com/marthoc/docker-deconz/issues/317

**Comment by xydix** [comment] 2020-12-15 23:47
Same problem here. Right now my deconz is down. Anyone got a solution? I tried downgrade to older version but no change. It have been running fine until I tried to upgrade deconz version same way I always do.

```
      
[marthoc/deconz] Starting deCONZ...


[marthoc/deconz] Current deCONZ version: 2.07.01


[marthoc/deconz] Web UI port: 8090


[marthoc/deconz] Websockets port: 440


[marthoc/deconz] VNC port: 5910


/usr/bin/xauth:  file /root/.Xauthority does not exist




New 'kitchen:10 (root)' desktop at :10 on machine k*n




Starting applications specified in /etc/X11/Xvnc-session


Log file is /root/.vnc/kitchen:10.log




Use xtigervncviewer -SecurityTypes VncAuth,TLSVnc -passwd /root/.vnc/passwd k*n:10 to connect to the VNC server.




QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-root'


QStandardPaths: wrong ownership on runtime directory /tmp/runtime-root, -2 instead of 0


libpng warning: iCCP: known incorrect sRGB profile


libpng warning: iCCP: known incorrect sRGB profile


00:41:16:152 HTTP Server listen on address 0.0.0.0, port: 8090, root: /usr/share/deCONZ/webapp/


00:41:16:161 CTRL. 3.27.200:41:16:199 dev can't create file: /dev/ttyACM0 via mknod (missing permissions)


00:41:16:200 ZCLDB init file /root/.local/share/dresden-elektronik/deCONZ/zcldb.txt


00:41:16:219 /usr/bin/../share/deCONZ/plugins no plugin directory found


00:41:16:234 dev can't create file: /dev/ttyACM0 via mknod (missing permissions)


00:41:17:251 dev can't create file: /dev/ttyACM0 via mknod (missing permissions)
```
I kown my stick is on /dev/ttyUSB0

**Comment by slusken** [comment] 2020-12-23 01:55
I had the same problem and everything started after I upgraded docker to 20.10.1.

I know that Home Assistant also had problem with docker 20.10.1.

So i took a change and installed 19.03.14 instead om my debian10 machine and everything start working again.

apt install docker-ce=5:19.03.14~3-0~debian-buster
apt install docker-ce-cli=5:19.03.14~3-0~debian-buster
apt install containerd.io=1.3.9-1

**Comment by RikP** [comment] 2020-12-23 09:02
I have Docker version 19.03.5, build 633a0ea838 installed, so this seems to be a different issue.

I can pinpoint it exactly that it happened after updating to docker-deconz 2.05.86

**Comment by Openhabber** [comment] 2020-12-25 23:14
I have exactly the same problem. Im on Synology NAS. The container worked before and does not after upgrade today. Everything is down.

**Comment by Openhabber** [comment] 2020-12-25 23:27
I just noticed, that i can temprarily get it to work by doing (device is available as /dev/deconz, as also given through the parameter DECONZ_DEVICE) :
`ln /dev/deconz /dev/ttyUSB0`
and for the message to disappear completely
`touch /dev/ttyACM0`

however, this will disappear after a container restart.....a fix is needed

**Comment by lubbertkramer** [comment] 2020-12-29 23:08
Can confirm this, just updated with conbee 2 and set the ttyACM0 with id to conbee (just like i did on earlier releases) Below my config, i have now replaced conbee for ttyACM0 and it's working

NUC with Ubuntu:

```
  deconz:
    container_name: deconz
    image: marthoc/deconz:amd64-2.09.00
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
      - DEBUG_INFO=1
      - DEBUG_APS=0
      - DEBUG_ZCL=0
      - DEBUG_ZDP=0
      - DEBUG_OTAU=1
      - DECONZ_DEVICE=/dev/ttyACM0
      # - DECONZ_DEVICE=/dev/conbee
      - DECONZ_WEB_PORT=8383
      - DECONZ_WS_PORT=8444
      - DECONZ_VNC_MODE=1
      - DECONZ_VNC_PORT=5900
      - DECONZ_VNC_PASSWORD=${DECONZVNC}
    network_mode: host
    ports:
      - 8383:8383
    volumes:
      - ${BASE}/deconz:/root/.local/share/dresden-elektronik/deCONZ
      - ${BASE}/deconz/otau:/root/otau
      - /etc/localtime:/etc/localtime:ro
    devices:
      - /dev/ttyACM0
      # - /dev/conbee
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:8383"]
      interval: 60s
      timeout: 30s
      retries: 6
    logging:
        options:
            max-size: 10m
```

**Comment by slusken** [comment] 2020-12-30 14:16
> 
> 
> Can confirm this also, just updated deconz with conbee 2 and set the ttyACM0 with id to conbee (just like i had on earlier releases) Below my config, i have now replaced conbee for ttyACM0 and it's working
> 
> Configuration:
> NUC with Ubuntu and Conbee 2 with deconz running in Docker
> 
> ```
>   deconz:
>     container_name: deconz
>     image: marthoc/deconz:amd64-2.09.00
>     environment:
>       - PUID=1000
>       - PGID=1000
>       - TZ=${TZ}
>       - DEBUG_INFO=1
>       - DEBUG_APS=0
>       - DEBUG_ZCL=0
>       - DEBUG_ZDP=0
>       - DEBUG_OTAU=1
>       - DECONZ_DEVICE=/dev/ttyACM0
>       # - DECONZ_DEVICE=/dev/conbee
>       - DECONZ_WEB_PORT=8383
>       - DECONZ_WS_PORT=8444
>       - DECONZ_VNC_MODE=1
>       - DECONZ_VNC_PORT=5900
>       - DECONZ_VNC_PASSWORD=${DECONZVNC}
>     network_mode: host
>     ports:
>       - 8383:8383
>     volumes:
>       - ${BASE}/deconz:/root/.local/share/dresden-elektronik/deCONZ
>       - ${BASE}/deconz/otau:/root/otau
>       - /etc/localtime:/etc/localtime:ro
>     devices:
>       - /dev/ttyACM0
>       # - /dev/conbee
>     healthcheck:
>       test: ["CMD", "curl", "-f", "http://127.0.0.1:8383"]
>       interval: 60s
>       timeout: 30s
>       retries: 6
>     logging:
>         options:
>             max-size: 10m
> ```

The problem that I have is that /dev/ttyACM0 is occupied by my Z-wave stick already? 

udevadm info -a -n /dev/ttyACM0 | grep '{idVendor}' | head -n1
ATTRS{idVendor}=="0658"
udevadm info -a -n /dev/ttyUSB0 | grep '{idVendor}' | head -n1
ATTRS{idVendor}=="0403"

0403 is conbee and 0658 is z-wave stick..

**Comment by RikP** [comment] 2021-01-03 11:39
> I just noticed, that i can temprarily get it to work by doing (device is available as /dev/deconz, as also given through the parameter DECONZ_DEVICE) :
> `ln /dev/deconz /dev/ttyUSB0`
> and for the message to disappear completely
> `touch /dev/ttyACM0`
> 
> however, this will disappear after a container restart.....a fix is needed

I got it to work with the following:
```
ln <DECONZ_DEVICE PARAMETER> /dev/ttyACM0
touch /dev/ttyACM0
```

For me the parameter = /dev/serial/by-id/usb-dresden_elektronik_ingenieurtechnik_GmbH_ConBee_II_DE2193941-if00

Is this something the devs can maybe add in the init of the container?

**Comment by Openhabber** [comment] 2021-01-03 14:35
As my Container worked before updating, this is clearly a bug. The Parameter DECONZ_DEVICE seems to not work correctly anymore...

**Comment by trailro** [comment] 2021-01-12 10:54
Has this issue been resolved? i have 2 deconz instances in docker - one using a locally plugged in conbee ii - on ttyACM0 and another conbee i - on ttyUSB0. The first works fine, but when i try to start another instance of deconz it only takes the ACM0 stick, and not the USB0 stick. It seems to ignore the DECONZ_DEVICE parameter. It only seem to work with v 2.05.75 which I must keep to get things functional.

**Comment by elbaek89** [comment] 2021-01-14 11:46
I have the same issue. Pulled the container, ran the firmware update of conbee 2 which all went well. Didn't manage to get the VNC up and running, but the phoscon web ui is available (but a little buggy. this may be due to connectivity issues). 

I get the same messages (didn't insert as code as this messed up the syntax): 

12:34:02:394 device disconnected reason: 4, index: 0
12:34:03:303 wait reconnect 15 seconds
12:34:03:395 dev can't create file: /dev/ttyACM0 via mknod (missing permissions)
12:34:03:395 dev can't create file: /dev/ttyUSB0 via mknod (missing permissions)
12:34:03:396 dev /dev/ttyAMA0
12:34:03:396 COM: /dev/ttyACM11 / serialno: , ConBee II
12:34:04:303 wait reconnect 14 seconds
12:34:05:303 wait reconnect 13 seconds
12:34:06:303 failed to reconnect to network try=6
12:34:06:304 wait reconnect 12 seconds
12:34:07:303 wait reconnect 11 seconds
12:34:08:303 wait reconnect 10 seconds
12:34:09:303 wait reconnect 9 seconds
12:34:10:302 wait reconnect 8 seconds
12:34:11:303 failed to reconnect to network try=7
12:34:11:304 wait reconnect 7 seconds
12:34:11:363 dev can't create file: /dev/ttyACM0 via mknod (missing permissions)
12:34:11:364 dev can't create file: /dev/ttyUSB0 via mknod (missing permissions)
12:34:11:364 dev /dev/ttyAMA0
12:34:12:303 wait reconnect 6 seconds
12:34:13:303 wait reconnect 5 seconds
12:34:14:303 wait reconnect 4 seconds
12:34:15:303 wait reconnect 3 seconds
12:34:16:303 failed to reconnect to network try=8
12:34:16:303 wait reconnect 2 seconds
12:34:17:303 wait reconnect 1 seconds
12:34:17:393 dev can't create file: /dev/ttyACM0 via mknod (missing permissions)
12:34:17:394 dev can't create file: /dev/ttyUSB0 via mknod (missing permissions)
12:34:17:394 dev /dev/ttyAMA0
12:34:17:394 COM: /dev/ttyACM11 / serialno: , ConBee II

As you can see, it has understood that the conbee is attacehd to ttyACM11.

**Comment by DennisGaida** [comment] 2021-01-18 10:16
Have a very similar issue. Do you want a new Github issue for this?

not working:
```
--device=/dev/ttyACM0
-e DECONZ_DEVICE=/dev/ttyACM0
```
working:
```
--device=/dev/serial/by-id/usb-dresden_elektronik_ingenieurtechnik_GmbH_ConBee_II_DE2141692-if00:/dev/ttyACM0
-e DECONZ_DEVICE=/dev/serial/by-id/usb-dresden_elektronik_ingenieurtechnik_GmbH_ConBee_II_DE2141692-if00
```
I have found this notation here: https://github.com/dresden-elektronik/deconz-rest-plugin/issues/3858#issuecomment-742518302

I do have a udev-rule for the device as well, so I actually would use `/dev/conbee` which is also not working:
`SUBSYSTEM=="ttyACM?", ATTRS{idVendor}=="1cf1", ATTRS{idProduct}=="0030", MODE:="0660", GROUP="dialout", SYMLINK+="conbee"`

When **not** using the docker-version everything is working as expected with no changes (i.e. using `/dev/conbee`)

**Comment by RikP** [comment] 2021-01-20 18:21
Mapping the device inside the container to /dev/ttyACM0 worked for me!

so --device=/dev/serial/by-id/usb-dresden_elektronik_ingenieurtechnik_GmbH_ConBee_II_DE2141692-if00:/dev/ttyACM0
(note the :/dev/ttyACM0) at the end!

Maybe this should be added to the doc :)

**Comment by mamoel666** [comment] 2021-01-27 18:52
Same message here (Synology NAS):
`dev can't create file: /dev/ttyACM0 via mknod (missing permissions)`

My Conbee II is connected to /dev/ttyACM2 (ttyACM0 is my ZWAVE stick) and this is also set correctly in the configuration.

![image](https://user-images.githubusercontent.com/45948842/106039151-10be2a80-60d9-11eb-9399-1295d0b173c0.png)

**Comment by RikP** [comment] 2021-01-27 18:55
> Same message here (Synology NAS):
> `dev can't create file: /dev/ttyACM0 via mknod (missing permissions)`
> 
> My Conbee II is connected to /dev/ttyACM2 (ttyACM0 is my ZWAVE stick) and this is also set correctly in the configuration.
> 
> ![image](https://user-images.githubusercontent.com/45948842/106039151-10be2a80-60d9-11eb-9399-1295d0b173c0.png)

try my comment above :)

**Comment by mamoel666** [comment] 2021-01-27 19:08
> try my comment above :)

Do i have to run this command from inside the container? What is 'so' doing and how to revert it? Do I have to repeat this after updating the image?

**Comment by RikP** [comment] 2021-01-27 19:12
So the place where you assign your /dev/ttyACM2 into the docker container i assume is something like:

--device /dev/ttyACM2

which should be:
-- device /dev/ttyACM2:/dev/ttyACM0

**Comment by Jo-Be-Co** [comment] 2021-01-27 21:29
@mamoel666 on your Diskstation you have to start the web-admin and enter the Docker-gui. Change the config of your container. Actually you would have a setting like in my screenshot some comment above: https://github.com/marthoc/docker-deconz/issues/325#issuecomment-738683220
So you don't have any options like `--device` but an environment entry for `DECONZ_DEVICE` where you put `/dev/ttyACM2:/dev/ttyACM0` as value.

**Comment by fromeijn** [comment] 2021-02-16 21:11
Seeing same issues :/

**Comment by bamboozila** [comment] 2021-02-19 15:19
Hi, this issue is from 2020 and the DECONZ_DEVICE environment variable is still not working.

Could you update the README if the device mapping is the way to go for this project?

**Comment by mingan666** [comment] 2021-02-21 12:23
Is this problem isolated to the device mapping?
Has anybody checked if the other variables work as intended?

**Comment by bamboozila** [comment] 2021-02-23 08:53
> Is this problem isolated to the device mapping?
> Has anybody checked if the other variables work as intended?

DECONZ_DEVICE does not work.

Docker mapping does though.
e.g: /dev/ttyConbee:/dev/ttyACM0

**Comment by mamoel666** [comment] 2021-02-23 09:48
I can confirm
`--device=/dev/ttyACM2:/dev/ttyACM0`
in `docker run` is working.

**Comment by mingan666** [comment] 2021-02-23 11:01
I was wondering it the other variables work, such as DECONZ_WEB_PORT or DECONZ_VNC_MODE.
Intering to know it the problem is only related to the DECONZ_DEVICE or if it is a general issue, maybe due to the new base image?

If I recall correctly the --device option does not work when running docker swarm mode.
[see documentation](https://docs.docker.com/compose/compose-file/compose-file-v3/#devices)

**Comment by mamoel666** [comment] 2021-02-23 11:10
> I was wondering it the other variables work, such as DECONZ_WEB_PORT or DECONZ_VNC_MODE.
> Intering to know it the problem is only related to the DECONZ_DEVICE or if it is a general issue, maybe due to the new base image?

They do (I use them for enabling VNC and changing the VNC password).
And even DECONC_DEVICE works (in some way). My Conbee II was working perfectly without `--device=/dev/ttyACM2:/dev/ttyACM0`.

With `--device=/dev/ttyACM2` and DECONZ_DEVICE set to `/dev/ttyACM2` the only problem were some random error messages in the log about ttyACM0. But all devices were working as expected.

**Comment by mingan666** [comment] 2021-02-23 11:59
So then the issue is not related to the environment handling as such...
I guess nobody found out why this happens? LIke if it is a deconz issue (not sure where to find which deconz is used in which image?) or if it is the docker image that caused the issue?

Like I said the --device option is not working when running in a docker swarm...

**Comment by Jo-Be-Co** [comment] 2021-02-23 12:50
Does anyone know of a place were there parameters of the `deconz` executable are explained?

**Comment by mingan666** [comment] 2021-02-23 13:43
Maybe possible to use --help on the cmdline?
Haven't found any documentation online.

**Comment by mingan666** [comment] 2021-02-23 14:06
Maybe this link helps
[https://github.com/dresden-elektronik/deconz-rest-plugin/wiki/deCONZ-command-line-parameters](https://github.com/dresden-elektronik/deconz-rest-plugin/wiki/deCONZ-command-line-parameters)

**Comment by Jo-Be-Co** [comment] 2021-02-23 16:13
Thanks for the link - google didn't show this on my search.

From what I can see here:
```
platform minimal
In case you want to start headless, use this parameter. In case you want to have access to deCONZ' GUI, just leave this parameter out.

Example: /usr/bin/deCONZ --platform minimal --auto-connect=1
```
The `platform`-Parameter should be send with a double-dash. The [start.sh](https://github.com/marthoc/docker-deconz/blob/master/amd64/root/start.sh#L45) uses only a single dash ...

Maybe the behaviour of `deconz` changed so that arguments are parsed differently. The `--dev=/dev/myTTY` could be skipped in that case. There should be a rework of the start script. Maybe the parameter could/should be placed more in front of the line also.

But: this may only come to an effect if deconz is started with VNC disabled - otherwise the platform parameter won't be added.

**Comment by mingan666** [comment] 2021-02-23 19:24
I've tested the latest image with the 2.05.84 deconz version and it works just fine.
Therefor it seems to be a pure deconz issue.

I've been looking searching on there discord channels and found the following link
[https://github.com/dresden-elektronik/deconz-rest-plugin/issues/4411](https://github.com/dresden-elektronik/deconz-rest-plugin/issues/4411) which seems to be the same issue...

The thread talks about RaspBee, but my docker seems to think thats what I'm using....
From the logs (2.05.84) :
`20:12:09:381 CTRL. 3.27.220:12:09:404 COM: --dev: /dev/conbeeII (RaspBee)`

**Comment by Mimiix** [comment] 2021-03-23 08:20
As there hasn't been any new replies and as there are newer versions, i'm closing this issue. If this needs to be re-opened, please ping me :)

**Closed by Mimiix** 2021-03-23 08:20 UTC
