### ISSUE TITLE
Firmware flashing failed libc 2.28 not found

### ISSUE THREAD

**Issue by schnuckz** [marthoc/docker-deconz#153] opened 2019-09-06 19:39 UTC
RaspberryPi latest Docker version on Raspbian Buster

`sudo docker run -it --rm --entrypoint "/firmware-update.sh" --privileged --cap-add=ALL -v /dev:/dev -v /lib/modules:/lib/modules -v /sys:/sys marthoc/deconz`

 `/usr/bin/GCFFlasher_internal.bin: /lib/arm-linux-gnueabihf/libc.so.6: version 'GLIBC_2.28' not found (required by /usr/lib/libwiringPi.so)`

On Container Debian Stretch the latest libc6 ist 2.24

**Comment by schnuckz** [comment] 2019-09-09 06:11
with custom docker build its worked

changing
`FROM balenalib/armv7hf-debian:stretch-run`

to
`FROM balenalib/armv7hf-debian:buster-run`

but not testing anything else
and switch back to `marthoc/docker-deconz:latest`

**Comment by jurikolo** [comment] 2019-09-13 10:46
Same issue here:
```
docker run -it --rm --entrypoint "/firmware-update.sh" --privileged --cap-add=ALL -v /dev:/dev -v /lib/modules:/lib/modules -v /sys:/sys marthoc/deconz:armhf-2.05.69
-------------------------------------------------------------------
 
             marthoc/deconz Firmware Flashing Script
 
                       Version: 0.5
 
-------------------------------------------------------------------
 
 
Listing attached devices...
 
/usr/bin/GCFFlasher_internal.bin: /lib/arm-linux-gnueabihf/libc.so.6: version `GLIBC_2.28' not found (required by /usr/lib/libwiringPi.so)
 
Enter the full device path, or press Enter now to exit.
 
Device Path : /dev/ttyAMA0
 
-------------------------------------------------------------------
 
Firmware available for flashing:
 
deCONZ_ConBeeII_0x26490700.bin.GCF
deCONZ_ConBeeII_0x264a0700.bin.GCF
deCONZ_Rpi_0x26330500.bin.GCF
 
Enter the firmware file name from above, including extension,
or press Enter now to exit.
 
File Name : deCONZ_Rpi_0x26330500.bin.GCF
 
-------------------------------------------------------------------
 
Device: /dev/ttyAMA0
 
Firmware File: deCONZ_Rpi_0x26330500.bin.GCF
 
Are the above device and firmware values correct?
Enter Y to proceed, any other entry to exit: Y
 
Flashing...
 
/usr/bin/GCFFlasher_internal.bin: /lib/arm-linux-gnueabihf/libc.so.6: version `GLIBC_2.28' not found (required by /usr/lib/libwiringPi.so)
 
Flashing Error! Please re-run this script...
```

```
cat /etc/os-release 
PRETTY_NAME="Raspbian GNU/Linux 9 (stretch)"
NAME="Raspbian GNU/Linux"
VERSION_ID="9"
VERSION="9 (stretch)"
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"
```

**Comment by FezVrasta** [comment] 2019-09-17 10:20
I can still reproduce this error with `docker run -it --rm --entrypoint "/firmware-update.sh" --privileged --cap-add=ALL -v /dev:/dev -v /lib/modules:/lib/modules -v /sys:/sys marthoc/deconz:armhf-2.05.69`

**Comment by marthoc** [comment] 2019-09-17 10:34
Yes I had to revert the fix - upgrading the images to Buster broke deconz for everyone. Still investigating a fix.

**Comment by FezVrasta** [comment] 2019-09-17 10:36
Oh, that's why it didn't work then...

Can I use `latest` to fix my setup or should I use an older image? I tried with `armhf-2.05.66` but my whole house is still dark :-(

**Comment by marthoc** [comment] 2019-09-17 10:40
What version of RPi are you on? Does this not work?
```
docker run -it --rm --entrypoint "/firmware-update.sh" --privileged --cap-add=ALL -v /dev:/dev -v /lib/modules:/lib/modules -v /sys:/sys marthoc/deconz:armhf-2.05.66
```

**Comment by FezVrasta** [comment] 2019-09-17 10:44
I'm on Raspberry Pi 4, yep your latest command is working

**Comment by FezVrasta** [comment] 2019-09-17 10:52
I updated the firmware and I'm running DeCONZ on the latest tag, but my lights are still not responding 😢

**Comment by almirdelkic** [comment] 2019-10-04 22:45
I am getting the same error using:
`docker run -it --rm --entrypoint "/firmware-update.sh" --privileged --cap-add=ALL -v /dev:/dev -v /lib/modules:/lib/modules -v /sys:/sys marthoc/deconz
`

**Comment by moritzschaefer** [comment] 2019-10-05 21:24
Fix is described here:
https://github.com/processone/ejabberd/issues/2650

1. Run bash in docker
docker run -it --rm --entrypoint /bin/bash --privileged --cap-add=ALL -v /dev:/dev -v /lib/modules:/lib/modules -v /sys:/sys marthoc/deconz

2. Add "deb http://ftp.de.debian.org/debian sid main" to /etc/apt/sources.list
and execute apt-get update && apt-get upgrade libc6
3. Execute /firmware-update.sh

@marthoc you could fix the image simply by adding the sid repository

**Comment by almirdelkic** [comment] 2019-10-05 22:03
I can confirm that updating libc6 works. Thanks @moritzschaefer

**Comment by alialrahma** [comment] 2019-10-30 21:28
I am unable to update marthoc/deconz too on my Conbee II running Version 2.05.67 Firmware 264A0700. This is the error message I get on RPi3B running Buster:

```
>> docker run -it --rm --entrypoint "/firmware-update.sh" --privileged --cap-add=ALL -v /dev:/dev -v /lib/modules:/lib/modules -v /sys:/sys marthoc/deconz

-------------------------------------------------------------------
 
Firmware available for flashing:
 
deCONZ_ConBeeII_0x26490700.bin.GCF
deCONZ_ConBeeII_0x264a0700.bin.GCF
deCONZ_Rpi_0x26330500.bin.GCF
 
Enter the firmware file name from above, including extension,
or press Enter now to exit.
 
File Name : deCONZ_ConBeeII_0x26490700.bin.GCF
 
-------------------------------------------------------------------
 
Device: /dev/ttyACM0
 
Firmware File: deCONZ_ConBeeII_0x26490700.bin.GCF
 
Are the above device and firmware values correct?
Enter Y to proceed, any other entry to exit: Y
 
Flashing...
 
/usr/bin/GCFFlasher_internal.bin: /lib/arm-linux-gnueabihf/libc.so.6: version `GLIBC_2.28' not found (required by /usr/lib/libwiringPi.so)
 
Flashing Error! Please re-run this script...
```

**Comment by msandres13** [comment] 2019-11-09 11:56
> Fix is described here:
> [processone/ejabberd#2650](https://github.com/processone/ejabberd/issues/2650)
> 
>     1. Run bash in docker
>        docker run -it --rm --entrypoint /bin/bash --privileged --cap-add=ALL -v /dev:/dev -v /lib/modules:/lib/modules -v /sys:/sys marthoc/deconz
> 
>     2. Add "deb http://ftp.de.debian.org/debian sid main" to /etc/apt/sources.list
>        and execute apt-get update && apt-get upgrade libc6
> 
>     3. Execute /firmware-update.sh
> 
> 
> @marthoc you could fix the image simply by adding the sid repository

Update worked for me as shown here. Raspberian Buster, Device Raspbee.
Thanks for posting this work around :-)

**Comment by BassdoxXx** [comment] 2020-03-26 16:55
> What version of RPi are you on? Does this not work?
> 
> ```
> docker run -it --rm --entrypoint "/firmware-update.sh" --privileged --cap-add=ALL -v /dev:/dev -v /lib/modules:/lib/modules -v /sys:/sys marthoc/deconz:armhf-2.05.66
> ```

This worked for me on Rpi3 Raspbian Stretch lite ! Thank you !

 docker run -it --rm --entrypoint "/firmware-update.sh" --privileged --cap-add=ALL -v /dev:/dev -v /lib/modules:/lib/modules -v /sys:/sys marthoc/deconz:armhf-2.05.66
Unable to find image 'marthoc/deconz:armhf-2.05.66' locally
armhf-2.05.66: Pulling from marthoc/deconz
2eead4197fac: Pull complete
8153c3bca43e: Pull complete
14ea784a6e70: Pull complete
d72fc803ed1c: Pull complete
eaa717024ffe: Pull complete
9a030514b0a1: Pull complete
503daa6aaad2: Pull complete
47f594c92ae1: Pull complete
068c8d1e96ba: Pull complete
c99abb6057dc: Pull complete
428fe717b0b0: Pull complete
79a5f8b3baf3: Pull complete
1de46aae08c0: Pull complete
8bd964d3c64a: Pull complete
ea99fa54a397: Pull complete
4344667c8f17: Pull complete
Digest: sha256:921b901a0831b7adc0af3261c4c89d2fa974cdb517195264344952b3b4b81d12
Status: Downloaded newer image for marthoc/deconz:armhf-2.05.66
-------------------------------------------------------------------

             marthoc/deconz Firmware Flashing Script

                       Version: 0.5

-------------------------------------------------------------------


Listing attached devices...

GCFFlasher V3_05 (c) dresden elektronik ingenieurtechnik gmbh
Path             | Vendor | Product | Serial     | Type
-----------------+--------+---------+------------+-------
/dev/ttyAMA0     | 0x0000 | 0x0000  |            | RaspBee

Enter the full device path, or press Enter now to exit.

Device Path : /dev/ttyAMA0

-------------------------------------------------------------------

Firmware available for flashing:

deCONZ_ConBeeII_0x26480700.bin.GCF
deCONZ_ConBeeII_0x26490700.bin.GCF
deCONZ_Rpi_0x261f0500.bin.GCF
deCONZ_Rpi_0x26320500.bin.GCF
deCONZ_Rpi_0x26330500.bin.GCF

Enter the firmware file name from above, including extension,
or press Enter now to exit.

File Name : deCONZ_Rpi_0x26330500.bin.GCF

-------------------------------------------------------------------

Device: /dev/ttyAMA0

Firmware File: deCONZ_Rpi_0x26330500.bin.GCF

Are the above device and firmware values correct?
Enter Y to proceed, any other entry to exit: Y

Flashing...

GCFFlasher V3_05 (c) dresden elektronik ingenieurtechnik gmbh
Reboot device /dev/ttyAMA0 (RaspBee)
deCONZ firmware version 26190500
action: reset device RaspBee
action: update firmware after 2 ms
semium
Vers. 1.02
build 2013/08/01
 (110 ms)
flashing 125684 bytes: |=============================|
verify: ....
SUCCESS

**Comment by hmrc87** [comment] 2020-05-09 11:14
> > What version of RPi are you on? Does this not work?
> > ```
> > docker run -it --rm --entrypoint "/firmware-update.sh" --privileged --cap-add=ALL -v /dev:/dev -v /lib/modules:/lib/modules -v /sys:/sys marthoc/deconz:armhf-2.05.66
> > ```
> 
> This worked for me on Rpi3 Raspbian Stretch lite ! Thank you !
> 
> ## docker run -it --rm --entrypoint "/firmware-update.sh" --privileged --cap-add=ALL -v /dev:/dev -v /lib/modules:/lib/modules -v /sys:/sys marthoc/deconz:armhf-2.05.66
> Unable to find image 'marthoc/deconz:armhf-2.05.66' locally
> armhf-2.05.66: Pulling from marthoc/deconz
> 2eead4197fac: Pull complete
> 8153c3bca43e: Pull complete
> 14ea784a6e70: Pull complete
> d72fc803ed1c: Pull complete
> eaa717024ffe: Pull complete
> 9a030514b0a1: Pull complete
> 503daa6aaad2: Pull complete
> 47f594c92ae1: Pull complete
> 068c8d1e96ba: Pull complete
> c99abb6057dc: Pull complete
> 428fe717b0b0: Pull complete
> 79a5f8b3baf3: Pull complete
> 1de46aae08c0: Pull complete
> 8bd964d3c64a: Pull complete
> ea99fa54a397: Pull complete
> 4344667c8f17: Pull complete
> Digest: sha256:921b901a0831b7adc0af3261c4c89d2fa974cdb517195264344952b3b4b81d12
> Status: Downloaded newer image for marthoc/deconz:armhf-2.05.66
> ```
>          marthoc/deconz Firmware Flashing Script
> 
>                    Version: 0.5
> ```
> 
> Listing attached devices...
> 
> GCFFlasher V3_05 (c) dresden elektronik ingenieurtechnik gmbh
> Path | Vendor | Product | Serial | Type
> -----------------+--------+---------+------------+-------
> /dev/ttyAMA0 | 0x0000 | 0x0000 | | RaspBee
> 
> Enter the full device path, or press Enter now to exit.
> 
> Device Path : /dev/ttyAMA0
> 
> Firmware available for flashing:
> 
> deCONZ_ConBeeII_0x26480700.bin.GCF
> deCONZ_ConBeeII_0x26490700.bin.GCF
> deCONZ_Rpi_0x261f0500.bin.GCF
> deCONZ_Rpi_0x26320500.bin.GCF
> deCONZ_Rpi_0x26330500.bin.GCF
> 
> Enter the firmware file name from above, including extension,
> or press Enter now to exit.
> 
> File Name : deCONZ_Rpi_0x26330500.bin.GCF
> 
> Device: /dev/ttyAMA0
> 
> Firmware File: deCONZ_Rpi_0x26330500.bin.GCF
> 
> Are the above device and firmware values correct?
> Enter Y to proceed, any other entry to exit: Y
> 
> Flashing...
> 
> GCFFlasher V3_05 (c) dresden elektronik ingenieurtechnik gmbh
> Reboot device /dev/ttyAMA0 (RaspBee)
> deCONZ firmware version 26190500
> action: reset device RaspBee
> action: update firmware after 2 ms
> semium
> Vers. 1.02
> build 2013/08/01
> (110 ms)
> flashing 125684 bytes: |=============================|
> verify: ....
> SUCCESS

Tried this on RPI 4 without luck

```
File Name : deCONZ_Rpi_0x26330500.bin.GCF

-------------------------------------------------------------------

Device: /dev/ttyAMA0

Firmware File: deCONZ_Rpi_0x26330500.bin.GCF

Are the above device and firmware values correct?
Enter Y to proceed, any other entry to exit: Y

Flashing...

GCFFlasher V3_05 (c) dresden elektronik ingenieurtechnik gmbh
Reboot device /dev/ttyAMA0 (RaspBee)
deCONZ firmware version 26050500
action: reset device RaspBee
action: update firmware after 2 ms
could not sync with bootloader

Flashing Error! Please re-run this script...
```

**Comment by hmrc87** [comment] 2020-05-09 11:42
> apt-get update && apt-get upgrade libc6

Thanks -> This worked on Raspberry Pi 4

**Comment by marhoy** [comment] 2020-05-23 16:15
I have the same issue on a Rpi3B, where I want to upgrade my Rasbee to firmware 0x26350500.
I've tried upgrading libc on armhf-2.05.76 (as described above), which didn't work:
```
Device: /dev/ttyAMA0

Firmware File: deCONZ_Rpi_0x26350500.bin.GCF

Are the above device and firmware values correct?
Enter Y to proceed, any other entry to exit: Y

Flashing...

GCFFlasher V3_13 (c) dresden elektronik ingenieurtechnik gmbh
Reboot device /dev/ttyAMA0 (RaspBee)

855: Error: (assert) n == CMD_deconzVersion.size()

Flashing Error! Please re-run this script...
```

..and I I've tried using an older version of the container (armhf-2.05.66) which also doesn't work because the latest firmware isn't included.

@marthoc Any progress on this?
I seem to be stuck...

**Comment by LightningRhino** [comment] 2020-05-24 10:51
Same problem here with the latest image (Image ID fd10c8d158a4):

> /usr/bin/GCFFlasher_internal.bin: /lib/arm-linux-gnueabihf/libc.so.6: version `GLIBC_2.28' not found (required by /usr/lib/libwiringPi.so)

> root@6c532c12296d:/# sudo apt-get install libc6
Reading package lists... Done
Building dependency tree       
Reading state information... Done
**libc6 is already the newest version** (2.24-11+deb9u4).

**Comment by marthoc** [comment] 2020-05-27 21:14
Closing this issue - please see #228 for updates on this problem.

**Closed by marthoc** 2020-05-27 21:15 UTC
