### ISSUE TITLE
port 443 is used, even when remapping the websocket port 8443 using the option `-e DECONZ_WS_PORT=8443`

### ISSUE THREAD

**Issue by michaelmell** [marthoc/docker-deconz#335] opened 2020-12-27 09:54 UTC
Hi,

**Issue:**

I am running the Deconz docker image and diyHue docker image on a Raspberry Pi 4. Even though I remap the Deconz websocket port to 8443, HTTPS does not work for diyHue, which uses port 443 (and since Hue expects fixed port-numbers, I cannot remap those of diyHue).

**Details**:

This is the docker run command that I use to start Deconz:

```
sudo docker run -d \
   --name=deconz \
   --net=host \
   -e DECONZ_WEB_PORT=8180 \
   -e DECONZ_WS_PORT=8443 \
   --restart=always \
   -v /etc/localtime:/etc/localtime:ro \
   -v ~/.local/share/dresden-elektronik/deCONZ:/root/.local/share/dresden-elektronik/deCONZ \
   --device=/dev/ttyACM0 \
   -e DECONZ_DEVICE=/dev/ttyACM0 \
   marthoc/deconz:stable
```

This is the output I get from `sudo netstat -tulpn | grep LISTEN`, which shows Deconz still using port 443:

```
tcp        0      0 0.0.0.0:9001            0.0.0.0:*               LISTEN      6686/node           
tcp        0      0 0.0.0.0:139             0.0.0.0:*               LISTEN      6716/smbd           
tcp        0      0 0.0.0.0:80              0.0.0.0:*               LISTEN      14033/python3       
tcp        0      0 0.0.0.0:8180            0.0.0.0:*               LISTEN      17801/deCONZ        
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      540/sshd            
tcp        0      0 0.0.0.0:443             0.0.0.0:*               LISTEN      17801/deCONZ        
tcp        0      0 0.0.0.0:445             0.0.0.0:*               LISTEN      6716/smbd           
tcp6       0      0 :::139                  :::*                    LISTEN      6716/smbd           
tcp6       0      0 :::5007                 :::*                    LISTEN      6685/java           
tcp6       0      0 :::8080                 :::*                    LISTEN      6685/java           
tcp6       0      0 :::22                   :::*                    LISTEN      540/sshd            
tcp6       0      0 :::8443                 :::*                    LISTEN      6685/java           
tcp6       0      0 :::445                  :::*                    LISTEN      6716/smbd           
tcp6       0      0 127.0.0.1:40419         :::*                    LISTEN      6685/java           
tcp6       0      0 127.0.0.1:8101          :::*                    LISTEN      6685/java
```

**Desired help:**

Please help me figure out how to free up the port 443.

**EDIT**

* I should add that I have confirmed, that HTTPS starts working for diyHue, when I stop the deconz container.

**Comment by tubalainen** [comment] 2020-12-27 12:13
Hi @michaelmell !

The problem is that you use the --net-host parameter causing deconz to default use the default ports.

Try:
```
sudo docker run -d \
   --name=deconz \
   --restart=always \
   -p 8180:80 \
   -p 8443:8443 \
   -e DECONZ_WEB_PORT=80 \
   -e DECONZ_WS_PORT=8443 \
   -v /etc/localtime:/etc/localtime:ro \
   -v ~/.local/share/dresden-elektronik/deCONZ:/root/.local/share/dresden-elektronik/deCONZ \
   --device=/dev/ttyACM0 \
   -e DECONZ_DEVICE=/dev/ttyACM0 \
   marthoc/deconz:stable
```

**Comment by michaelmell** [comment] 2020-12-27 19:10
Hi @tubalainen,
thank you for your quick reply.
I tried your command, but get the following error:

```
docker: Error response from daemon: driver failed programming external connectivity on endpoint deconz (06974539fcd961f5e17b77f098133808083b5c8a2556dc1fc52aa7ae2e1f2819): Error starting userland proxy: listen tcp 0.0.0.0:8443: bind: address already in use.
```

I also tried a couple of variations. In particular remapping the ports without the options `DECONZ_WEB_PORT` and `DECONZ_WS_PORT`, but that gives the same error:

```
sudo docker run -d \
  --name=deconz \
  --restart=always \
  -p 8180:80 \
  -p 8443:443 \
  -v /etc/localtime:/etc/localtime:ro \
  -v ~/.local/share/dresden-elektronik/deCONZ:/root/.local/share/dresden-elektronik/deCONZ \
  --device=/dev/ttyACM0 \
  -e DECONZ_DEVICE=/dev/ttyACM0 \
  marthoc/deconz:stable
```

I confirmed that the previous version using `--net=host \` does still work, so it is not because I messed up my ports somehow.

Any suggestions? Because I am stuck ...

**Comment by michaelmell** [comment] 2020-12-27 19:14
@tubalainen nevermind. it seems to be because that port is already in use. Mapping to a different port seems to solve the issue. I will update/close the ticket, if I get things resolved. Sorry for spamming.

**Comment by tubalainen** [comment] 2020-12-27 21:02
No worries, glad to hear it worked out. 👍

**Comment by Mimiix** [comment] 2021-03-23 08:20
As there hasn't been any new replies and as there are newer versions, i'm closing this issue. If this needs to be re-opened, please ping me :)

**Closed by Mimiix** 2021-03-23 08:20 UTC
