### ISSUE TITLE
DECONZ_DEVICE ignored in 2.05.88?

### ISSUE THREAD

**Issue by oddeirik** [marthoc/docker-deconz#308] opened 2020-11-14 15:13 UTC
I just updated to the latest deconz Docker image, and now the container can't connect to the device any longer.

Edit: Reverted back to v2.05.84 and it's working again. Exact same container arguments.

The container is started with the following arguments, which has worked fine up until now:
`docker run -d --name=deconz --net=host --restart=always -v /etc/localtime:/etc/localtime:ro -v /opt/deconz:/root/.local/share/dresden-elektronik/deCONZ --device=/dev/ttyUSB-Zigbee -e DECONZ_WEB_PORT=8080 -e DECONZ_WS_PORT=8443 -e TZ=Europe/Oslo -e DECONZ_DEVICE=/dev/ttyUSB-Zigbee -e DECONZ_VNC_MODE=1 -e DECONZ_VNC_PASSWORD=REDACTED -e DECONZ_UPNP=0 marthoc/deconz`

But in the container logs, I can see it's still trying to use dev/ttyAMA0 as the device, which of course fails:

```[marthoc/deconz] Starting deCONZ...
[marthoc/deconz] Current deCONZ version: 2.05.88
[marthoc/deconz] Web UI port: 8080
[marthoc/deconz] Websockets port: 8443
[marthoc/deconz] VNC port: 5900
/usr/bin/xauth:  file /root/.Xauthority does not exist

New 'raspberrypi:0 (root)' desktop at :0 on machine raspberrypi

Starting applications specified in /etc/X11/Xvnc-session
Log file is /root/.vnc/raspberrypi:0.log

Use xtigervncviewer -SecurityTypes VncAuth,TLSVnc -passwd /root/.vnc/passwd raspberrypi:0 to connect to the VNC server.

QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-root'
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
16:05:44:322 HTTP Server listen on address 0.0.0.0, port: 8080, root: /usr/share/deCONZ/webapp/
16:05:44:351 CTRL. 3.27.216:05:44:438 dev /dev/ttyAMA0
16:05:44:487 dev /dev/ttyAMA0
16:05:44:488 ZCLDB init file /root/.local/share/dresden-elektronik/deCONZ/zcldb.txt
16:05:44:655 parent process /bin/sh
16:05:44:655 gw run mode: docker
16:05:44:655 GW sd-card image version file does not exist: /root/.local/share/dresden-elektronik/deCONZ/gw-version
16:05:44:656 sd-card cid: 035344534336344780ffffffff013900
16:05:44:657 DB sqlite version 3.27.2
16:05:44:658 DB PRAGMA page_count: 33
16:05:44:658 DB PRAGMA page_size: 4096
16:05:44:658 DB PRAGMA freelist_count: 0
16:05:44:659 DB file size 135168 bytes, free pages 0
16:05:44:659 DB PRAGMA user_version: 7
16:05:44:659 DB cleanup
16:05:44:660 DB create temporary views
16:05:44:667 started websocket server at port 8443
16:05:44:670 [INFO] - Found file containing button maps. Parsing data...
16:05:44:672 [ERROR] - Button map 'sunricherCCTMap' in JSON file has no assigned ModelIDs. Skip loading button map...
16:05:44:679 [INFO] - Button maps loaded.
16:05:44:681 dlg action: Read binding table
16:05:44:681 found node plugin: libde_rest_plugin.so - REST API Plugin
16:05:44:684 found node plugin: libde_signal_plugin.so - Signal Monitor Plugin
16:05:44:698 found node plugin: libstd_otau_plugin.so - STD OTAU Plugin
16:05:44:747 dev /dev/ttyAMA0
16:05:44:798 dev /dev/ttyAMA0
16:05:45:848 dev /dev/ttyAMA0
16:05:45:897 dev /dev/ttyAMA0
16:05:45:918 device disconnected reason: 4, index: 0
16:05:46:750 wait reconnect 15 seconds
16:05:46:801 dev /dev/ttyAMA0
16:05:46:850 dev /dev/ttyAMA0
16:05:47:699 wait reconnect 14 seconds
16:05:48:663 wait reconnect 13 seconds
16:05:49:664 wait reconnect 12 seconds
16:05:49:968 dev /dev/ttyAMA0
16:05:50:663 wait reconnect 11 seconds
16:05:50:745 Announced to internet http://dresden-light.appspot.com/discover
16:05:50:745 discovery server date: Sat, 14 Nov 2020 15:05:50 GMT
16:05:50:746     local time seems to be ok
16:05:50:746 discovery found version 2.04.35 for update channel stable
16:05:51:664 wait reconnect 10 seconds```

**Comment by damajor** [comment] 2020-11-14 17:03
I got the same issue.:

On 84 it works fine:
```
17:59:46:001 COM: /dev/ttyAMA0 :  (0x0000/0x0000)
17:59:46:001 dev /dev/ttyAMA0
17:59:46:001 COM: /dev/ttyS0 :  (0x0000/0x0000)
17:59:46:001 COM: --dev: /dev/ttyS0 (RaspBee)
17:59:46:001 auto connect com /dev/ttyS0
```
with config:
```
    devices:
      - /dev/ttyAMA0
      - /dev/ttyS0
    environment:
      - DECONZ_DEVICE=/dev/ttyS0
```

With latest docker image I got the same logs as @oddeirik and my RaspBee 2 is not found.

**Comment by marthoc** [comment] 2020-11-14 17:44
Can you try using privileged mode? I’m trying to track down this issue with the newer versions.

**Comment by oddeirik** [comment] 2020-11-14 18:24
Tried privileged mode, didn't make any difference. It's still hell bent on using /dev/ttyAMA0 as the device.

I also tried starting deCONZ via a shell using the same container arguments as the firmware update script (which does work, btw, I updated successfully to the latest firmware included. So it can definitely access the device if required, it just seems like deCONZ itself ignores the `--dev` argument.

**Comment by tubalainen** [comment] 2020-11-14 19:39
Have you guys tried to unplug/replug the USB dongle? I had similar issues myself a year or so ago and that sorted my issue.

**Comment by damajor** [comment] 2020-11-14 19:45
I use RaspBee 2 on GPIO so not USB.
And when I switch back to version 84 or 85 or 86 it is working fine, without rebooting. So the device state may not be the root cause of the issue.

**Comment by oddeirik** [comment] 2020-11-14 20:09
Yeah, tried replugging the device and rebooting the Pi as well. The only change from that was that the ConBee II changed from ttyACM1 to ttyACM2, hence the udev rules in place to always map it to ttyUSB-Zigbee 😛 

(And as mentioned, 84 works fine.)

**Comment by damajor** [comment] 2020-11-14 21:30
Ok that looks like a Windows support solution "Try to reboot!!'  😛

But I did it and still the same.
FYI there is no special udev rules in Raspbian that is renaming the serial device to ttyUSB-Zigbee or something similar...
There is no /dev/serial/ directory either.

84/85 and 86 are working. Not 87 neither 88.

**Comment by damajor** [comment] 2020-11-14 22:42
Don't know if it will help but after complete container removal, it works.
So docker should do something with the attached devices during all my tests.
I use a compose file and to make 88 to work, I had to:
 - modify the compose file (pass both devices ttyAMA0 & ttyS0, and I do not use DECONZ_DEVICE anymore)
 - stop the current container
 - rm the container
 - docker compose up again

And voila.

**Comment by FuzzyMistborn** [comment] 2020-11-15 01:41
I tried those steps and I'm still not having luck getting the container to run, even on .84.  I tried updating my Conbee's firmware and even that's not getting me anywhere.  What I get for updating on a Saturday night (my fault, just venting at myself not devs):

```
[marthoc/deconz] Starting deCONZ...,
[marthoc/deconz] Current deCONZ version: 2.05.88,
[marthoc/deconz] Web UI port: 100,
[marthoc/deconz] Websockets port: 460,
[marthoc/deconz] VNC Disabled,
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-root',
libpng warning: iCCP: known incorrect sRGB profile,
20:39:23:127 HTTP Server listen on address 0.0.0.0, port: 100, root: /usr/share/deCONZ/webapp/,
20:39:23:146 CTRL. 3.27.220:39:23:177 ZCLDB init file /root/.local/share/dresden-elektronik/deCONZ/zcldb.txt,
20:39:23:231 parent process /bin/sh,
20:39:23:231 gw run mode: docker,
20:39:23:231 GW sd-card image version file does not exist: /root/.local/share/dresden-elektronik/deCONZ/gw-version,
20:39:23:234 DB sqlite version 3.27.2,
20:39:23:234 DB PRAGMA page_count: 33,
20:39:23:234 DB PRAGMA page_size: 4096,
20:39:23:234 DB PRAGMA freelist_count: 0,
20:39:23:234 DB file size 135168 bytes, free pages 0,
20:39:23:234 DB PRAGMA user_version: 7,
20:39:23:234 DB cleanup,
20:39:23:234 DB create temporary views,
20:39:23:238 started websocket server at port 460,
20:39:23:240 [INFO] - Found file containing button maps. Parsing data...,
20:39:23:241 [ERROR] - Button map 'sunricherCCTMap' in JSON file has no assigned ModelIDs. Skip loading button map...,
20:39:23:243 [INFO] - Button maps loaded.,
20:39:23:244 dlg action: Read binding table,
20:39:23:244 found node plugin: libde_rest_plugin.so - REST API Plugin,
20:39:23:245 found node plugin: libde_signal_plugin.so - Signal Monitor Plugin,
20:39:23:251 found node plugin: libstd_otau_plugin.so - STD OTAU Plugin,
This plugin does not support propagateSizeHints(),
This plugin does not support propagateSizeHints(),
20:39:24:291 COM check bootloader,
20:39:24:303 ,
R21B18 Bootloader,
20:39:24:303 Vers: 2.07,
20:39:24:303 build: Jun 17 2019,
20:39:24:303 , 08:48:53,
20:39:26:293 COM check bootloader,
20:39:26:305 ,
R21B18 Bootloader,
20:39:26:305 Vers: 2.07,
20:39:26:305 build: Jun 17 2019,
20:39:26:305 , 08:48:53,
20:39:26:662 New websocket 192.168.10.10:48560 (state: 3) ,
20:39:28:304 COM check bootloader,
20:39:28:316 ,
R21B18 Bootloader,
20:39:28:316 Vers: 2.07,
20:39:28:316 build: Jun 17 2019,
20:39:28:316 , 08:48:53,
20:39:28:658 Announced to internet http://dresden-light.appspot.com/discover,
20:39:29:395 New websocket 192.168.30.20:53786 (state: 3) ,
20:39:30:315 COM check bootloader,
20:39:30:326 ,
R21B18 Bootloader,
20:39:30:326 Vers: 2.07,
20:39:30:326 build: Jun 17 2019,
20:39:30:326 , 08:48:53,
20:39:32:316 COM check bootloader,
20:39:32:327 ,
R21B18 Bootloader,
20:39:32:327 Vers: 2.07,
20:39:32:327 build: Jun 17 2019,
20:39:32:327 , 08:48:53,
20:39:34:326 COM check bootloader,
20:39:34:337 ,
R21B18 Bootloader,
20:39:34:337 Vers: 2.07,
20:39:34:337 build: Jun 17 2019,
20:39:34:337 , 08:48:53,
20:39:36:328 COM check bootloader,
20:39:36:339 ,
R21B18 Bootloader,
20:39:36:339 Vers: 2.07,
20:39:36:339 build: Jun 17 2019,
20:39:36:339 , 08:48:53,
20:39:36:340 device disconnected reason: 5, index: 0,
20:39:36:457 wait reconnect 15 seconds,
20:39:37:456 wait reconnect 14 seconds,
20:39:37:980 GW update firmware found: /usr/share/deCONZ/firmware/deCONZ_ConBeeII_0x26660700.bin.GCF,
20:39:38:457 wait reconnect 13 seconds,
20:39:39:456 wait reconnect 12 seconds,
20:39:40:456 wait reconnect 11 seconds,
```

**Comment by damajor** [comment] 2020-11-15 02:42
My Raspbee 2 (GPIO not USB) has firmware 26660700
I run it on RPi 3b
And here is my compose file
```
  deconz:
    image: marthoc/deconz:armhf #-2.05.84
    container_name: deconz
    network_mode: host
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /home/pi/docker/deconz:/root/.local/share/dresden-elektronik/deCONZ
    devices:
      - /dev/ttyAMA0
      - /dev/ttyS0
    environment:
      - DECONZ_WEB_PORT=8070
      - DECONZ_WS_PORT=9443
      - DEBUG_INFO=0
      - DEBUG_APS=0
      - DEBUG_ZCL=0
      - DEBUG_ZDP=0
      - DEBUG_OTAU=0
      - TZ=Europe/Paris
      - DECONZ_VNC_MODE=1
      - DECONZ_VNC_PORT=5900
      - DECONZ_VNC_PASSWORD=******
      #- DECONZ_DEVICE=/dev/ttyS0
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8090" ]
      start_period: 30s
```
Now it seems to run fine on every version from 84 to 88.

**Comment by FuzzyMistborn** [comment] 2020-11-15 03:04
Not working for me.  Here's my compose:

```
  deconz:
    container_name: deConz
    image: marthoc/deconz:amd64-2.05.84
    volumes:
      - ./hass_docker/deconz:/root/.local/share/dresden-elektronik/deCONZ
    ports:
      - "100:100"
      - "460:460"
    devices:
#      - /dev/serial/by-id/usb-dresden_elektronik_ingenieurtechnik_GmbH_ConBee_II_DE2152697-if00:/dev/serial/by-id/usb-dresden_elektronik_ingenieurtechnik_GmbH_ConBee_II_DE2152697-if00
      - /dev/ttyACM0:/dev/ttyACM0
    environment:
      - DECONZ_WEB_PORT=100
      - DECONZ_WS_PORT=460
#      - DECONZ_DEVICE=/dev/ttyACM0
#      - DECONZ_DEVICE=/dev/serial/by-id/usb-dresden_elektronik_ingenieurtechnik_GmbH_ConBee_II_DE2152697-if00
      - TZ=${TZ}
    network_mode: host
    privileged: true
    restart: always
```
I've been playing with various versions of DECONZ_DEVICE and device paths.  Before I had the serial path and it worked fine.

**Comment by hre1** [comment] 2020-11-15 17:12
same here (no device --> version v2.5.86 works without problems):

`docker run --detach --restart=always --net=host -e DECONZ_WEB_PORT=8000 -e DECONZ_WS_PORT=8043 -e TZ='Europe/Berlin' -e DEBUG_INFO=1 -e DECONZ_VNC_MODE=1 -e DECONZ_VNC_PORT=5900 -e DECONZ_VNC_PASSWORD=changeme --volume /stripe/opt/docker/data/volumes/deconz:/root/.local/share/dresden-elektronik/deCONZ --device=/dev/ConBeeII -e DECONZ_DEVICE=/dev/ConBeeII --name deconz-vnc-V2_5_88 marthoc/deconz`





`[marthoc/deconz] Starting deCONZ...
[marthoc/deconz] Current deCONZ version: 2.05.88
[marthoc/deconz] Web UI port: 8000
[marthoc/deconz] Websockets port: 8043
[marthoc/deconz] VNC port: 5900
Killing Xtigervnc process ID 24... which was already dead
Cleaning stale pidfile '/root/.vnc/ha-node2.hre:0.pid'!
Cleaning stale x11 lock '/tmp/.X0-lock'!
Cleaning stale x11 lock '/tmp/.X11-unix/X0'!

New 'ha-node2.hre:0 (root)' desktop at :0 on machine ha-node2.hre

Starting applications specified in /etc/X11/Xvnc-session
Log file is /root/.vnc/ha-node2.hre:0.log

Use xtigervncviewer -SecurityTypes VncAuth,TLSVnc -passwd /root/.vnc/passwd ha-node2.hre:0 to connect to the VNC server.

QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-root'
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
17:53:59:892 HTTP Server listen on address 0.0.0.0, port: 8000, root: /usr/share/deCONZ/webapp/
17:53:59:905 CTRL. 3.27.217:53:59:000 ZCLDB init file /root/.local/share/dresden-elektronik/deCONZ/zcldb.txt
17:54:00:139 parent process /bin/sh
17:54:00:139 gw run mode: docker
17:54:00:140 GW sd-card image version file does not exist: /root/.local/share/dresden-elektronik/deCONZ/gw-version
17:54:00:140 DB sqlite version 3.27.2
17:54:00:141 DB PRAGMA page_count: 44
17:54:00:141 DB PRAGMA page_size: 4096
17:54:00:141 DB PRAGMA freelist_count: 1
17:54:00:142 DB file size 180224 bytes, free pages 1
17:54:00:142 DB PRAGMA user_version: 7
17:54:00:142 DB cleanup
17:54:00:142 DB create temporary views
17:54:00:151 started websocket server at port 8043
17:54:00:153 [INFO] - Found file containing button maps. Parsing data...
17:54:00:154 [ERROR] - Button map 'sunricherCCTMap' in JSON file has no assigned ModelIDs. Skip loading button map...
17:54:00:158 [INFO] - Button maps loaded.
17:54:00:160 dlg action: Read binding table
17:54:00:160 found node plugin: libde_rest_plugin.so - REST API Plugin
17:54:00:162 found node plugin: libde_signal_plugin.so - Signal Monitor Plugin
17:54:00:171 found node plugin: libstd_otau_plugin.so - STD OTAU Plugin
17:54:01:320 device disconnected reason: 4, index: 0
17:54:02:190 wait reconnect 15 seconds
17:54:03:141 wait reconnect 14 seconds
17:54:03:705 New websocket 10.20.20.223:55098 (state: 3)
17:54:04:091 wait reconnect 13 seconds
17:54:05:063 wait reconnect 12 seconds
17:54:06:063 wait reconnect 11 seconds
17:54:06:286 Announced to internet http://dresden-light.appspot.com/discover
17:54:07:063 wait reconnect 10 seconds
17:54:08:063 wait reconnect 9 seconds
17:54:09:063 wait reconnect 8 seconds
17:54:10:063 wait reconnect 7 seconds
17:54:11:063 wait reconnect 6 seconds
17:54:12:063 wait reconnect 5 seconds
17:54:13:063 wait reconnect 4 seconds
17:54:14:063 wait reconnect 3 seconds
17:54:15:063 wait reconnect 2 seconds
17:54:15:597 GW update firmware found: /usr/share/deCONZ/firmware/deCONZ_ConBeeII_0x26660700.bin.GCF
17:54:16:063 wait reconnect 1 seconds
17:54:16:139 device disconnected reason: 4, index: 0
17:54:17:063 wait reconnect 15 seconds
17:54:18:063 wait reconnect 14 seconds
`

**Comment by FuzzyMistborn** [comment] 2020-11-16 17:22
Partly able to resolve my issues by getting a good flash of the latest firmware using an Ubuntu desktop instead of the docker image (that may be a separate issue but not one I'll dive into atm).  Still having the same issues with .88 as others but got .84 working for now.  So if anybody is having issues, try a different method of flashing the firmware to rule that out as a possible problem.

**Comment by manup** [comment] 2020-11-17 19:59
Hi, this is a regression since v2.5.87.
This is now fixed for upcoming releases: https://github.com/dresden-elektronik/deconz-rest-plugin/issues/3681#issuecomment-729102833

Currently RaspBee I and II works only for device paths:
`/dev/ttyAMA0` and symlinked `/dev/serial0`  &rarr; `/dev/ttyS0` in the container.

Note both depend on how the UART is configured as described in https://www.raspberrypi.org/documentation/configuration/uart.md

**Comment by Mimiix** [comment] 2021-03-23 08:03
As there hasn't been any new replies and as there are newer versions, i'm closing this issue. If this needs to be re-opened, please ping me :)

**Closed by Mimiix** 2021-03-23 08:03 UTC
