### ISSUE TITLE
Run container with VNC enabled? Deconz won't start

### ISSUE THREAD

**Issue by xydix** [marthoc/docker-deconz#134] opened 2019-06-22 19:49 UTC
This is what I get in my log when I try to enable VNC.

[marthoc/deconz] Starting deCONZ...

[marthoc/deconz] Current deCONZ version: 2.05.66

[marthoc/deconz] Web UI port: 8090

[marthoc/deconz] Websockets port: 440

[marthoc/deconz] VNC Display: :0 on port 5900

tigervncserver: /usr/bin/Xtigervnc did not start up, please look into '/root/.vnc/kitchen:0.log' to determine the reason! -2

Invalid MIT-MAGIC-COOKIE-1 keyQXcbConnection: Could not connect to display :0

Aborted (core dumped)

[marthoc/deconz] Starting deCONZ...

[marthoc/deconz] Current deCONZ version: 2.05.66

[marthoc/deconz] Web UI port: 8090

[marthoc/deconz] Websockets port: 440

[marthoc/deconz] VNC Display: :0 on port 5900

tigervncserver: /usr/bin/Xtigervnc did not start up, please look into '/root/.vnc/kitchen:0.log' to determine the reason! -2

Invalid MIT-MAGIC-COOKIE-1 keyQXcbConnection: Could not connect to display :0

Aborted (core dumped)

**Comment by marthoc** [comment] 2019-07-25 18:11
Try setting the VNC port env var to a different value to see if that fixes this problem.

**Comment by agners** [comment] 2019-08-05 23:11
FWIW, VNC port was the issue in my case with the very same error message. Thanks!

**Comment by xydix** [comment] 2019-08-21 20:20
Solved it. Thank you.

**Comment by ReekyMarko** [comment] 2019-10-27 11:24
Had the same problem here. IMO the default should be changed to something else or we should investigate the actual cause of this crash.

**Comment by marthoc** [comment] 2019-10-27 12:24
The cause is that your system does not have display :0 available. Changing the port also changes the display, they are linked. There is a way to fix it less bluntly and I will investigate.

**Comment by marthoc** [comment] 2020-05-27 21:11
Closing this given the age of the issue, please open a new issue if this is still relevant.

**Closed by marthoc** 2020-05-27 21:11 UTC
